export const NEXTERA_INDEX_PRIMER_P5_ADAPTER_SEQ = 'AATGATACGGCGACCACCGAGATCTACAC'
export const NEXTERA_INDEX_PRIMER_R1_BINDING_SEQ = 'TCGTCGGCAGCGTC'

export const NEXTERA_INDEX_PRIMER_P7_ADAPTER_SEQ = 'CAAGCAGAAGACGGCATACGAGAT'
export const NEXTERA_INDEX_PRIMER_R2_BINDING_SEQ = 'GTCTCGTGGGCTCGG'

export const LABELSEQ_INDEX_PRIMER_P5_ADAPTER_SEQ = 'AATGATACGGCGACCACCGAGATCTACAC'
export const LABELSEQ_INDEX_PRIMER_R1_BINDING_SEQ = 'CTAGATGATCCGAGTGATCCTGCGtgtcgagtagagtgtggg'

export const LABELSEQ_INDEX_PRIMER_P7_ADAPTER_SEQ = 'AGAAGGGTCATAGGACTAGTCACTA'
export const LABELSEQ_INDEX_PRIMER_R2_BINDING_SEQ = 'CCGATCTGTGCAGAGTTACGACTCGTCGTCACTAG'

export const RETRIEVER_PRIMER_FORWARD_ADAPTER_SEQ = 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
export const RETRIEVER_PRIMER_REVERSE_ADAPTER_SEQ = 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
